Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-06, with the labels that each got.

#1228 fix: More heading levels so RNs resolve links
  docs/conf.py
Labels: documentation

#1221 fix: constructor LLM should not skip loading other config models
  nemoguardrails/rails/llm/llmrails.py
  tests/test_llama_guard.py
  tests/test_llmrails.py
  tests/test_patronus_lynx.py
Labels: bug, status: in review

#1207 fix(content_safety): replace try-except with iterable unpacking for policy violations
  nemoguardrails/library/content_safety/actions.py
Labels: bug, status: in review

#1249 fix(jailbreak): pin numpy==1.23.5 for scikit-learn compatibility
  nemoguardrails/library/jailbreak_detection/requirements.txt
Labels: bug

#1242 fix(output_parsers): iterable unpacking compatibility in content safety parsers
  nemoguardrails/library/self_check/facts/actions.py
  nemoguardrails/library/self_check/input_check/actions.py
  nemoguardrails/library/self_check/output_check/actions.py
  nemoguardrails/llm/output_parsers.py
  tests/test_content_safety_integration.py
  tests/test_content_safety_output_parsers.py
Labels: bug

#1247 fix: register main LLM as action parameter when initialized from config
  nemoguardrails/rails/llm/llmrails.py
  tests/test_llmrails.py
Labels: bug
