Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-01, with the labels that each got.

#828 ci: Add Dependabot
  .github/dependabot.yml
Labels: CI

#923 Chore/deps poetry version
  CONTRIBUTING.md
  pyproject.toml
Labels: dependencies

#901 feat: add pii masking capability to private ai integration
  docs/user-guides/community/privateai.md
  docs/user-guides/guardrails-library.md
  examples/configs/privateai/pii_masking/config.yml
  examples/notebooks/privateai_pii_detection.ipynb
  nemoguardrails/library/privateai/actions.py
  nemoguardrails/library/privateai/flows.co
  nemoguardrails/library/privateai/flows.v1.co
  nemoguardrails/library/privateai/request.py
  tests/test_privateai.py
Labels: enhancement, status: in review

#845 feat: add score threshold to AnalyzerEngine
  docs/user-guides/community/presidio.md
  nemoguardrails/library/sensitive_data_detection/actions.py
  nemoguardrails/rails/llm/config.py
  tests/test_sensitive_data_detection.py
Labels: enhancement, status: waiting confirmation, status: in review

#946 Fix: Handle unescaped quotes in generate_value using safe_eval
  nemoguardrails/actions/llm/generation.py
  nemoguardrails/utils.py
  tests/test_utils.py
Labels: enhancement

#956 Build docs with docs deps and make
  .github/workflows/docs-build.yaml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-remove-stale-reviews.yaml
  .gitlab-ci.yml
  CONTRIBUTING.md
  Makefile
  README.md
  docs/README.md
  docs/conf.py
  docs/index.md
  docs/project.json
  docs/user-guides/advanced/jailbreak-detection-heuristics-deployment.md
  docs/versions1.json
  poetry.lock
  pyproject.toml
Labels: documentation

#958 Use ref name as dir for push build
  .github/workflows/docs-build.yaml
Labels: documentation

#957 Typos with oauthtoken
  docs/user-guides/advanced/nemoguard-contentsafety-deployment.md
  docs/user-guides/advanced/nemoguard-topiccontrol-deployment.md
Labels: documentation

#939 chore(deps): update httpx and related dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#897 fix: handle non-relative file paths
  nemoguardrails/actions/action_dispatcher.py
  tests/test_action_dispatcher.py
Labels: bug, status: in review

#898 feat: add embedding_params to BasicEmbeddingsIndex
  nemoguardrails/embeddings/basic.py
  nemoguardrails/embeddings/providers/__init__.py
  nemoguardrails/embeddings/providers/fastembed.py
  nemoguardrails/embeddings/providers/nim.py
  nemoguardrails/embeddings/providers/openai.py
  nemoguardrails/embeddings/providers/sentence_transformers.py
  nemoguardrails/rails/llm/llmrails.py
  tests/test_embedding_providers.py
  tests/test_embeddings_fastembed.py
Labels: enhancement, status: in review
