Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-05, with the labels that each got.

#1106 feat: add support for system messages to RunnableRails
  nemoguardrails/integrations/langchain/runnable_rails.py
  tests/test_runnable_rails.py
Labels: status: in review

#1142 feat: Add api_key_env_var to Model, pass in kwargs to langchain initializer
  examples/configs/content_safety_api_keys/README.md
  examples/configs/content_safety_api_keys/config.yml
  examples/configs/content_safety_api_keys/prompts.yml
  nemoguardrails/llm/models/initializer.py
  nemoguardrails/llm/models/langchain_initializer.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llmrails.py
  tests/llm_providers/test_langchain_initialization_methods.py
  tests/llm_providers/test_langchain_integration.py
  tests/test_rails_config.py
Labels: enhancement

#1147 refactor(llmrails)!: remove deprecated return_context argument
  nemoguardrails/rails/llm/llmrails.py
Labels: refactoring

#1161 fix(config): correct dialog rails activation logic
  nemoguardrails/rails/llm/config.py
  tests/test_config_validation.py
Labels: bug, enhancement, refactoring

#1164 feat: add inline YARA rules support
  nemoguardrails/library/injection_detection/actions.py
  nemoguardrails/rails/llm/config.py
  tests/test_injection_detection.py
Labels: enhancement

#1145 feat!: add support for preserving and optionally applying guardrails to reasoning traces
  nemoguardrails/actions/llm/generation.py
  nemoguardrails/actions/llm/utils.py
  nemoguardrails/actions/v2_x/generation.py
  nemoguardrails/context.py
  nemoguardrails/library/content_safety/actions.py
  nemoguardrails/library/self_check/facts/actions.py
  nemoguardrails/library/self_check/input_check/actions.py
  nemoguardrails/library/self_check/output_check/actions.py
  nemoguardrails/llm/filters.py
  nemoguardrails/llm/taskmanager.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llmrails.py
  tests/conftest.py
  tests/test_configs/with_custom_llm_prompt_action_v2_x/actions.py
  tests/test_filters.py
  tests/test_llmrails_reasoning.py
  tests/test_llmrails_reasoning_output_rails.py
  tests/test_reasoning_trace_context.py
  tests/test_reasoning_traces.py
Labels: enhancement, refactoring

#1169 feat: prevent reasoning traces from contaminating LLM prompt history
  nemoguardrails/llm/taskmanager.py
  tests/test_llm_task_manager.py
Labels: enhancement

#1171 ci: add Python 3.12 and 3.13 test jobs to gitlab workflow
  .gitlab-ci.yml
Labels: CI

#1181 docs: clarify purpose of model parameters field in configuration guide
  docs/user-guides/configuration-guide.md
Labels: documentation

#1007 docs: Output rails are supported with streaming
  docs/user-guides/advanced/streaming.md
Labels: documentation

#1196 refactor(config): update deprecated field handling for remove_thinking_traces
  nemoguardrails/rails/llm/config.py
Labels: enhancement

#1140 Fix/community integrations colang2
  nemoguardrails/library/privateai/actions.py
  nemoguardrails/library/privateai/flows.co
  nemoguardrails/library/prompt_security/flows.co
  nemoguardrails/library/prompt_security/flows.v1.co
Labels: bug

#1182 fix(tests): ensure proper asyncio task cleanup in test_streaming_handler.py
  tests/test_streaming_handler.py
Labels: status: in review

#1183 test(streaming): add extensive tests for StreamingHandler to enhance coverage
  tests/test_streaming_handler.py
Labels: status: in review

#1185 refactor(streaming): introduce END_OF_STREAM sentinel and update handling
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/streaming.py
  tests/test_streaming_handler.py
Labels: bug, enhancement, status: in review

#1199 feat: add Nemotron model support with message-based prompts
  examples/configs/nemotron/README.md
  examples/configs/nemotron/config.yml
  nemoguardrails/llm/prompts.py
  nemoguardrails/llm/prompts/llama3.yml
  nemoguardrails/llm/prompts/nemotron_reasoning.yml
  nemoguardrails/rails/llm/llmrails.py
  tests/test_nemotron_prompt_modes.py
  tests/test_system_message_conversion.py
Labels: enhancement

#1136 chore: Identify OS packages to intstall
  CONTRIBUTING.md
Labels: documentation

#1159 docs: fix output rail doc
  docs/getting-started/5-output-rails/README.md
  docs/user-guides/configuration-guide.md
Labels: documentation

#1144 docs: Possible update to injection detection
  docs/user-guides/guardrails-library.md
  examples/configs/injection_detection/config/config.yml
  examples/configs/injection_detection/demo-out.txt
  examples/configs/injection_detection/demo.py
Labels: documentation

#1141 docs: Add release notes
  docs/conf.py
  docs/index.md
  docs/release-notes.md
Labels: documentation
