Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-07, with the labels that each got.

#1260 feat(jailbreak): Add direct API key configuration support
  examples/configs/jailbreak_detection_nim/README.md
  examples/configs/jailbreak_detection_nim/config.yml
  nemoguardrails/library/jailbreak_detection/actions.py
  nemoguardrails/rails/llm/config.py
  tests/test_jailbreak_config.py
Labels: enhancement

#1272 docs: release notes 0.14.1
  docs/project.json
  docs/release-notes.md
  docs/versions1.json
Labels: documentation

#1274 Update docs to use `nim_base_url` per new configuration.
  docs/user-guides/advanced/nemoguard-jailbreakdetect-deployment.md
Labels: documentation

#1281 ci(dependabot): remove dependabot configuration
  .github/dependabot.yml
Labels: CI

#1276 docs: fix page-not-appearing issue
  docs/index.md
  docs/user-guides/advanced/index.rst
Labels: documentation

#1259 fix(streaming): resolve word concatenation in streaming output rails
  nemoguardrails/rails/llm/buffer.py
  nemoguardrails/rails/llm/llmrails.py
  tests/test_buffer_strategy.py
  tests/test_streaming.py
Labels: bug, enhancement, status: in review, refactoring

#1264 fix: enable token usage tracking for streaming LLM calls
  nemoguardrails/rails/llm/llmrails.py
  poetry.lock
  pyproject.toml
  tests/test_callbacks.py
  tests/test_llmrails.py
  tests/test_token_usage_integration.py
  tests/utils.py
Labels: bug, status: in review

#1269 feat(tracing)!: update tracing to use otel api
  examples/configs/tracing/README.md
  examples/configs/tracing/working_example.py
  nemoguardrails/tracing/adapters/opentelemetry.py
  poetry.lock
  pyproject.toml
  tests/test_tracing_adapters_opentelemetry.py
Labels: enhancement, status: in review

#1263 feat: implement parallel streaming output rails execution
  nemoguardrails/colang/runtime.py
  nemoguardrails/colang/v1_0/runtime/runtime.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llmrails.py
  tests/test_parallel_streaming_output_rails.py
Labels: enhancement, status: in review

#1286 feat(streaming): support external async token generators
  docs/user-guides/advanced/streaming.md
  nemoguardrails/rails/llm/llmrails.py
  tests/test_streaming_output_rails.py
Labels: enhancement

#1234 feat: parallel rails execution
  nemoguardrails/colang/runtime.py
  nemoguardrails/colang/v1_0/runtime/flows.py
  nemoguardrails/colang/v1_0/runtime/runtime.py
  nemoguardrails/logging/processing_log.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llm_flows.co
  nemoguardrails/rails/llm/llmrails.py
  tests/test_configs/parallel_rails/actions.py
  tests/test_configs/parallel_rails/config.yml
  tests/test_configs/parallel_rails/prompts.yml
  tests/test_configs/parallel_rails/rails/blocked_terms.co
  tests/test_parallel_rails.py
Labels: enhancement, status: in review

#1295 docs: add parallel rail section + split config page
  docs/index.md
  docs/release-notes.md
  docs/user-guides/configuration-guide.md
  docs/user-guides/configuration-guide/custom-initialization.md
  docs/user-guides/configuration-guide/exceptions.md
  docs/user-guides/configuration-guide/general-options.md
  docs/user-guides/configuration-guide/guardrails-configuration.md
  docs/user-guides/configuration-guide/index.md
  docs/user-guides/configuration-guide/knowledge-base.md
  docs/user-guides/configuration-guide/llm-configuration.md
  docs/user-guides/configuration-guide/tracing-configuration.md
  docs/user-guides/index.rst
Labels: documentation

#1309 ci: add release workflow
  .github/workflows/create-tag.yml
  .github/workflows/release.yml
  cliff.toml
Labels: CI
