Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-04, with the labels that each got.

#1081 fix(docs): remove markup from code block
  docs/user-guides/configuration-guide.md
Labels: documentation

#1090 chore(deps): update NVIDIA theme for Sphinx
  poetry.lock
  pyproject.toml
Labels: dependencies

#1098 chore: Add link to topic control config and prompts
  docs/user-guides/advanced/nemoguard-topiccontrol-deployment.md
Labels: documentation

#1083 refactor(llm): reorganize HuggingFace provider structure
  examples/configs/llm/hf_pipeline_dolly/config.py
  examples/configs/llm/hf_pipeline_falcon/config.py
  examples/configs/llm/hf_pipeline_llama2/config.py
  examples/configs/llm/hf_pipeline_mosaic/config.py
  examples/configs/llm/hf_pipeline_vicuna/config.py
  examples/configs/rag/multi_kb/config.py
  nemoguardrails/llm/providers/huggingface/__init__.py
  nemoguardrails/llm/providers/huggingface/pipeline.py
Labels: status: in review, refactoring

#1077 docs: remove NeMo Service (nemollm) related documentation
  docs/evaluation/README.md
  docs/user-guides/configuration-guide.md
  docs/user-guides/llm-support.md
Labels: documentation

#1079 ci: reorganize GitHub workflows for clear purpose and optimized coverage
  .github/workflows/full-tests.yml
  .github/workflows/latest-deps-tests.yml
  .github/workflows/pr-tests.yml
  .github/workflows/test-and-build-wheel.yml
Labels: status: in review

#1076 refactor(providers): remove support for deprecated nemollm engine
  examples/configs/llm/nemollm/README.md
  examples/configs/llm/nemollm/config.yml
  examples/configs/llm/nemollm/rails.co
  examples/configs/streaming/config.yml
  nemoguardrails/llm/filters.py
  nemoguardrails/llm/prompts/nemollm.yml
  nemoguardrails/llm/providers/nemollm.py
  nemoguardrails/llm/providers/providers.py
  nemoguardrails/llm/taskmanager.py
  tests/constants.py
  tests/llm_providers/test_nemollm.py
  tests/test_bug_5.py
  tests/test_configs/autoalign/config.yml
  tests/test_configs/autoalign_groundness/config.yml
  tests/test_configs/fact_checking/config.yml
  tests/test_configs/with_prompt_modes/prompts/prompts.yml
  tests/test_fact_checking.py
  tests/test_prompt_modes.py
Labels: status: in review, refactoring

#1088 feat(cli): add fuzzy find provider capability to cli
  nemoguardrails/cli/__init__.py
  nemoguardrails/cli/providers.py
  nemoguardrails/llm/providers/__init__.py
  nemoguardrails/llm/providers/providers.py
  tests/test_provider_selection.py
Labels: enhancement

#1089 docs(cli): add providers fuzzy search cli command
  docs/user-guides/cli.md
  docs/user-guides/configuration-guide.md
Labels: documentation

#1126 fix: self check output colang 1 flow
  nemoguardrails/library/self_check/output_check/flows.v1.co
Labels: bug

#1091 feat: add code injection detection to guardrails library
  docs/user-guides/guardrails-library.md
  nemoguardrails/library/injection_detection/__init__.py
  nemoguardrails/library/injection_detection/actions.py
  nemoguardrails/library/injection_detection/flows.co
  nemoguardrails/library/injection_detection/flows.v1.co
  nemoguardrails/library/injection_detection/yara_config.py
  nemoguardrails/library/injection_detection/yara_rules/code.yara
  nemoguardrails/library/injection_detection/yara_rules/sqli.yara
  nemoguardrails/library/injection_detection/yara_rules/template.yara
  nemoguardrails/library/injection_detection/yara_rules/xss.yara
  nemoguardrails/rails/llm/config.py
  poetry.lock
  pyproject.toml
  tests/test_configs/injection_detection/config.yml
  tests/test_configs/injection_detection/flows.co
  tests/test_configs/injection_detection/test.yara
  tests/test_injection_detection.py
Labels: enhancement, status: in review

#1133 chore: fix and revert poetry lock to its stable state
  .github/workflows/latest-deps-tests.yml
  .github/workflows/test-and-build-wheel.yml
  poetry.lock
  pyproject.toml
  tests/test_embeddings_only_user_messages.py
  tests/test_sensitive_data_detection.py
Labels: dependencies

#1027 Feature/clavata integration #1025
  .vscode/settings.json
  docs/user-guides/community/clavata.md
  examples/configs/clavata/README.md
  examples/configs/clavata/config.yml
  examples/configs/clavata_v2/README.md
  examples/configs/clavata_v2/config.yml
  examples/configs/clavata_v2/main.co
  examples/configs/clavata_v2/rails.co
  examples/notebooks/clavataai_detection.ipynb
  nemoguardrails/library/clavata/__init__.py
  nemoguardrails/library/clavata/actions.py
  nemoguardrails/library/clavata/errs.py
  nemoguardrails/library/clavata/flows.co
  nemoguardrails/library/clavata/flows.v1.co
  nemoguardrails/library/clavata/request.py
  nemoguardrails/library/clavata/utils.py
  nemoguardrails/rails/llm/config.py
  tests/test_clavata.py
  tests/test_clavata_models.py
  tests/test_clavata_utils.py
Labels: status: in review

#1137 feat: implement validation to forbid dialog rails with reasoning traces
  nemoguardrails/rails/llm/config.py
  tests/test_config_validation.py
  tests/test_dialog_tasks.py
Labels: enhancement
