Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-08, with the labels that each got.

#1323 fix(runtime): stop execution after internal error
  nemoguardrails/colang/v1_0/runtime/runtime.py
  tests/test_internal_error_parallel_rails.py
Labels: bug

#1315 docs: release notes for 0.15 and more doc fixes
  docs/project.json
  docs/release-notes.md
  docs/user-guides/advanced/streaming.md
  docs/user-guides/configuration-guide/guardrails-configuration.md
  docs/user-guides/configuration-guide/tracing-configuration.md
  docs/user-guides/tracing/index.md
  docs/versions1.json
Labels: documentation

#1317 fix: respect the user-provided log options regardless of tracing configuration
  nemoguardrails/rails/llm/llmrails.py
  tests/test_tracing.py
Labels: bug

#1330 docs: add kv cache reuse documentation
  docs/conf.py
  docs/index.md
  docs/user-guides/advanced/kv-cache-reuse.md
Labels: documentation

#1335 fix(topic_safety): handle InternalEvent objects in topic safety actions for Colang 2.0
  nemoguardrails/library/topic_safety/actions.py
  tests/test_topic_safety_internalevent.py
Labels: bug, colang 2.0

#1300 feat: add Pangea AI Guard community integration
  docs/user-guides/community/pangea.md
  docs/user-guides/guardrails-library.md
  docs/user-guides/llm-support.md
  examples/configs/pangea/README.md
  examples/configs/pangea/config.yml
  examples/configs/pangea_v2/README.md
  examples/configs/pangea_v2/config.yml
  examples/configs/pangea_v2/main.co
  examples/configs/pangea_v2/rails.co
  examples/configs/pangea_v2_no_llm/config.yml
  examples/configs/pangea_v2_no_llm/main.co
  examples/configs/pangea_v2_no_llm/rails.co
  nemoguardrails/library/pangea/__init__.py
  nemoguardrails/library/pangea/actions.py
  nemoguardrails/library/pangea/flows.co
  nemoguardrails/library/pangea/flows.v1.co
  nemoguardrails/rails/llm/config.py
  tests/test_pangea_ai_guard.py
Labels: enhancement

#1341 refactor(llmrails): move get_action_details_from_flow_id to utils
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/rails/llm/utils.py
  tests/test_llmrails.py
  tests/test_llmrails_reasoning.py
  tests/test_rails_llm_utils.py
Labels: refactoring

#1349 docs: doc edits for tracing notebook
  docs/getting-started/8-tracing/1_tracing_quickstart.ipynb
  docs/user-guides/tracing/adapter-configurations.md
  docs/user-guides/tracing/index.md
Labels: documentation
