Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-09, with the labels that each got.

#1354 docs: Integrate with multilingual NIM
  docs/index.md
  docs/user-guides/advanced/nemotron-content-safety-multilingual-deployment.md
Labels: documentation

#1346 fix(jailbreak): handle URL joining with/without trailing slashes
  nemoguardrails/library/jailbreak_detection/request.py
  tests/test_jailbreak_request.py
Labels: bug

#1402 ci: enable codecov for all pull requests
  .github/workflows/test-coverage-report.yml
Labels: CI

#1364 feat(tool-calling): add tool call passthrough support in LLMRails
  nemoguardrails/actions/llm/utils.py
  nemoguardrails/context.py
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/rails/llm/options.py
  tests/rails/llm/test_options.py
  tests/test_tool_calling_passthrough_integration.py
  tests/test_tool_calling_utils.py
  tests/test_tool_calls_context.py
Labels: enhancement

#1366 feat(runnable-rails): update RunnableRails with full LangChain Runnable protocol support
  nemoguardrails/integrations/langchain/runnable_rails.py
  tests/runnable_rails/test_basic_operations.py
  tests/runnable_rails/test_batch_as_completed.py
  tests/runnable_rails/test_batching.py
  tests/runnable_rails/test_composition.py
  tests/runnable_rails/test_format_output.py
  tests/runnable_rails/test_history.py
  tests/runnable_rails/test_piping.py
  tests/runnable_rails/test_runnable_rails.py
  tests/runnable_rails/test_streaming.py
  tests/runnable_rails/test_tool_calling.py
  tests/runnable_rails/test_transform_input.py
  tests/runnable_rails/test_types.py
  tests/utils.py
Labels: enhancement, runnable

#1369 feat(runnable-rails): implement AIMessage metadata parity in RunnableRails
  nemoguardrails/actions/llm/utils.py
  nemoguardrails/context.py
  nemoguardrails/integrations/langchain/runnable_rails.py
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/rails/llm/options.py
  tests/runnable_rails/test_metadata.py
  tests/runnable_rails/test_runnable_rails.py
Labels: enhancement, runnable

#1370 feat(runnable-rails): stream metadata in RunnableRails output
  nemoguardrails/integrations/langchain/runnable_rails.py
  tests/runnable_rails/test_metadata.py
  tests/runnable_rails/test_streaming.py
Labels: enhancement, runnable

#1382 feat(tool-rails): add support for tool output rails and validation
  nemoguardrails/actions/llm/generation.py
  nemoguardrails/actions/llm/utils.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llm_flows.co
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/rails/llm/options.py
  tests/runnable_rails/test_tool_calling.py
  tests/test_bot_tool_call_events.py
  tests/test_output_rails_tool_calls.py
  tests/test_tool_calling_passthrough_integration.py
  tests/test_tool_calling_passthrough_only.py
  tests/test_tool_calls_event_extraction.py
  tests/test_tool_output_rails.py
Labels: enhancement

#1414 docs: add tools integration guide
  docs/index.md
  docs/user-guides/advanced/tools-integration.md
Labels: documentation

#1423 docs: make some doc edits
  docs/user-guides/langchain/langgraph-integration.md
Labels: documentation

#1425 chore(docs): Update repository owner
  .github/workflows/docs-build.yaml
Labels: documentation, CI

#1419 docs(langchain): update with full support and add tool calling guide …
  docs/user-guides/langchain/runnable-rails.md
Labels: documentation
