Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-03, with the labels that each got.

#1014 CI: Extend latest deps tests to use macOS and Windows
  .github/workflows/_test.yml
  .github/workflows/latest-deps-tests.yml
Labels: CI

#996 Feat: Support Models with Reasoning Traces
  docs/user-guides/configuration-guide.md
  examples/configs/llm/deepseek-r1/config.yml
  nemoguardrails/library/self_check/facts/actions.py
  nemoguardrails/library/self_check/input_check/actions.py
  nemoguardrails/library/self_check/output_check/actions.py
  nemoguardrails/llm/filters.py
  nemoguardrails/llm/prompts.py
  nemoguardrails/llm/prompts/deepseek.yml
  nemoguardrails/llm/providers/providers.py
  nemoguardrails/llm/taskmanager.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llmrails.py
  tests/test_filters.py
  tests/test_jailbreak_models.py
  tests/test_llmrails_reasoning.py
Labels: documentation, enhancement

#999 replace FastAPI lifecycle management to use lifespan context manager
  nemoguardrails/server/api.py
Labels: enhancement

#1011 feat(streaming): add generation metadata to streaming chunks
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/streaming.py
Labels: enhancement, MS

#878 Improve alpha to beta bot migration
  nemoguardrails/cli/migration.py
  tests/test_cli_migration.py
Labels: status: in review

#1012 fix(llmrails): propagate errors in streaming mode
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/utils.py
  tests/test_streaming.py
  tests/test_utils.py
  tests/utils.py
Labels: bug, status: in review, MS

#1045 fix: enable output rails streaming explicitly
  nemoguardrails/actions/llm/generation.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llmrails.py
  tests/test_streaming_output_rails.py
Labels: status: in review

#1053 fix: improve multimodal prompt length calculation for base64 images
  nemoguardrails/llm/filters.py
  nemoguardrails/llm/taskmanager.py
  tests/test_llm_task_manager_multimodal.py
Labels: status: in review

#1058 feat: improve output rails error handling for SSE format
  docs/user-guides/configuration-guide.md
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/utils.py
  tests/test_streaming.py
  tests/test_streaming_output_rails.py
  tests/test_utils.py
Labels: enhancement, MS

#1062 docs: revise reasoning model info
  docs/user-guides/configuration-guide.md
Labels: documentation

#1005 docs: Consider new GS experience
  docs/getting-started.md
  docs/index.md
  examples/configs/gs_content_safety/config/config.yml
  examples/configs/gs_content_safety/config/prompts.yml
  examples/configs/gs_content_safety/demo-out.txt
  examples/configs/gs_content_safety/demo.py
Labels: documentation

#1071 docs: Updates for release
  docs/project.json
  docs/versions1.json
Labels: documentation
