Repository NVIDIA-NeMo/Guardrails, pull requests merged in 2025-02, with the labels that each got.

#965 Feat: Unified Output Mapping for Actions
  nemoguardrails/actions/actions.py
  nemoguardrails/library/activefence/actions.py
  nemoguardrails/library/autoalign/actions.py
  nemoguardrails/library/cleanlab/actions.py
  nemoguardrails/library/content_safety/actions.py
  nemoguardrails/library/factchecking/align_score/actions.py
  nemoguardrails/library/gcp_moderate_text/actions.py
  nemoguardrails/library/hallucination/actions.py
  nemoguardrails/library/jailbreak_detection/actions.py
  nemoguardrails/library/llama_guard/actions.py
  nemoguardrails/library/patronusai/actions.py
  nemoguardrails/library/privateai/actions.py
  nemoguardrails/library/prompt_security/actions.py
  nemoguardrails/library/self_check/facts/actions.py
  nemoguardrails/library/self_check/input_check/actions.py
  nemoguardrails/library/self_check/output_check/actions.py
  nemoguardrails/library/sensitive_data_detection/actions.py
  nemoguardrails/library/topic_safety/actions.py
  tests/test_actions.py
  tests/test_actions_server.py
Labels: enhancement, status: in review

#973 Remove docs CI to troubleshoot
  .gitlab-ci.yml
Labels: documentation

#975 chore(ci): Restore docs CI
  .gitlab-ci.yml
  docs/conf.py
Labels: documentation

#966 Feat: Output Rails Streaming
  nemoguardrails/actions/actions.py
  nemoguardrails/actions/llm/generation.py
  nemoguardrails/actions/output_mapping.py
  nemoguardrails/cli/chat.py
  nemoguardrails/logging/callbacks.py
  nemoguardrails/rails/llm/buffer.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/rails/llm/llmrails.py
  nemoguardrails/streaming.py
  tests/test_actions_output_mapping.py
  tests/test_buffer_strategy.py
  tests/test_llmrails.py
  tests/test_streaming.py
Labels: documentation, enhancement

#977 ci: add upgrade-deps option to test workflow
  .github/workflows/_test.yml
  .github/workflows/latest-deps-tests.yml
Labels: CI

#976 docs: output rails streaming
  docs/getting-started/5-output-rails/README.md
  docs/index.rst
  docs/project.json
  docs/user-guides/configuration-guide.md
  docs/versions1.json
Labels: documentation

#982 fix: fix alignscore dependency resolution in Dockerfile
  nemoguardrails/library/factchecking/align_score/Dockerfile
  nemoguardrails/library/factchecking/align_score/constraints.txt
  nemoguardrails/library/factchecking/align_score/requirements.txt
Labels: bug

#1009 YAML indent two spaces
  .vscode/settings.json
Labels: skip-changelog

#1013 chore(deps): cap spacy to <3.8.0 due to blis issue
  poetry.lock
  pyproject.toml
Labels: bug

#988 Feat: Add SHA-256 hashing option
  docs/user-guides/advanced/embedding-search-providers.md
  nemoguardrails/embeddings/cache.py
  nemoguardrails/kb/kb.py
  nemoguardrails/rails/llm/config.py
  nemoguardrails/utils.py
  tests/test_cache_embeddings.py
  tests/test_utils.py
Labels: enhancement
